spring.application.name=telemedicine-clinic-system

spring.datasource.url=jdbc:mysql://localhost:3306/telemedicine
spring.datasource.username=telemeduser
spring.datasource.password=Telemed123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true