spring.application.name=telemedicine-clinic-system

spring.datasource.url=jdbc:mysql://localhost:3306/telemedicine?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=895cf711ac3bbb
spring.mail.password=97b14248cf502d
spring.application.name=telemedicine-clinic-system

spring.datasource.url=jdbc:mysql://localhost:3306/telemedicine?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=895cf711ac3bbb
spring.mail.password=97b14248cf502d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=noreply@telemedclinic.com
server.address=0.0.0.0
server.port=8088

# Midtrans Configuration
midtrans.server.key=SB-Mid-server-FZvYihzxrtMX5BzlVSIJznZA
midtrans.client.key=SB-Mid-client-ttL1qeTBjl7ZG4Ad
midtrans.is.production=false
midtrans.api.url=https://app.sandbox.midtrans.com/snap/v1/transactions
